# Generated by Django 5.0.4 on 2024-06-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='service',
            field=models.TextField(),
        ),
    ]
