# Generated by Django 5.0.4 on 2024-06-19 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_submission_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contact',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
