name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Switch to Ubuntu (Linux) runner

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DATABASE_URL: mysql://myuser:mypassword@127.0.0.1:3306/mydatabase
      DJANGO_SECRET_KEY: your_secret_key
      DJANGO_SETTINGS_MODULE: your_project.settings

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mysqlclient  # Ensure MySQL client is installed

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h"127.0.0.1" --silent; then
              break
            fi
            echo 'Waiting for MySQL...'
            sleep 1
          done

      - name: Set up Database
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test


