# Generated by Django 5.0.4 on 2024-06-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
